# Generated by Django 5.1.5 on 2025-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_like_unique_together_remove_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sketches/', verbose_name='Зображення ескізу'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
