# Generated by Django 5.1.5 on 2025-05-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_sketch_image_alter_user_avatar'),
    ]

    operations = [
    ]
